data_mortality_multiple_2010 <- tribble(
    ~name, ~start, ~end, ~size, ~type, ~description, ~codes,
    "reserved_1", 1, 19, 19, "str", "Reserved Positions", "",
    "resident_status", 20, 20, 1, "int", "Resident status", "1=Residents|2=Intrastate Nonresidents|3=Interstate Nonresidents|4=Foreign Residents",
    "reserved_2", 21, 60, 40, "str", "Reserved Positions", "",
    "education_1989_rev", 61, 62, 2, "int", "Education (1989 revision)", "00=No formal education|01=Years of elementary school|09=1 year of high school|10=2 years of high school|11=3 years of high school|12=4 years of high school|13=1 year of college|14=2 years of college|15=3 years of college|16=4 years of college|17=5 or more years of college|99=Not stated",
    "education_2003_rev", 63, 63, 1, "int", "Education (2003 revision)", "1=8th grade or less|2=9-12th grade no diploma|3=high school graduate or GED completed|4=some college credit but no degree|5=Associate degree|6=Bachelor degree|7=Master degree|8=Doctorate or professional degree|9=Unknown",
    "education_reporting_flag", 64, 64, 1, "int", "Education reporting flag", "0=1989 revision of education item on certificate|1=2003 revision of education item on certificate|2=no education item on certificate",
    "month_of_death", 65, 66, 2, "int", "Month of death", "01=January|02=February|03=March|04=April|05=May|06=June|07=July|08=August|09=September|10=October|11=November|12=December",
    "reserved_3", 67, 68, 2, "str", "Reserved Positions", "",
    "sex", 69, 69, 1, "str", "Sex", "M=Male|F=Female",
    "detail_age", 70, 73, 4, "int", "Detail age", "1=Years|2=Months|4=Days|5=Hours|6=Minutes|9=Age not stated",
    "age_substitution_flag", 74, 74, 1, "str", "Age substitution flag", "1=Calculated age is substituted for reported age|blank=Calculated age is not substituted for reported age",
    "age_recode_52", 75, 76, 2, "int", "Age recode 52", "01=Under 1 hour|52=Age not stated",
    "age_recode_27", 77, 78, 2, "int", "Age recode 27", "01=Under 1 month|27=Age not stated",
    "age_recode_12", 79, 80, 2, "int", "Age recode 12", "01=Under 1 year|12=Age not stated",
    "infant_age_recode_22", 81, 82, 2, "int", "Infant age recode 22", "01=Under 1 hour|22=11 months",
    "place_of_death", 83, 83, 1, "int", "Place of death and status", "1=Hospital, clinic or Medical Center - Inpatient|2=Hospital, Clinic or Medical Center - Outpatient or admitted to Emergency Room|3=Hospital, Clinic or Medical Center - Dead on Arrival|4=Decedent’s home|5=Hospice facility|6=Nursing home/long term care|7=Other|9=Place of death unknown",
    "marital_status", 84, 84, 1, "str", "Marital status", "S=Never married, single|M=Married|W=Widowed|D=Divorced|U=Marital Status unknown",
    "day_of_week_of_death", 85, 85, 1, "int", "Day of week of death", "1=Sunday|2=Monday|3=Tuesday|4=Wednesday|5=Thursday|6=Friday|7=Saturday|9=Unknown",
    "reserved_4", 86, 101, 16, "str", "Reserved Positions", "",
    "current_data_year", 102, 105, 4, "int", "Current data year", "2010=2010",
    "injury_at_work", 106, 106, 1, "str", "Injury at work", "Y=Yes|N=No|U=Unknown",
    "manner_of_death", 107, 107, 1, "str", "Manner of death", "1=Accident|2=Suicide|3=Homicide|4=Pending investigation|5=Could not determine|6=Self-Inflicted|7=Natural|blank=Not specified",
    "method_of_disposition", 108, 108, 1, "str", "Method of disposition", "B=Burial|C=Cremation|O=Other|U=Unknown",
    "autopsy", 109, 109, 1, "str", "Autopsy", "Y=Yes|N=No|U=Unknown",
    "reserved_5", 110, 143, 34, "str", "Reserved Positions", "",
    "activity_code", 144, 144, 1, "int", "Activity code", "0=While engaged in sports activity|1=While engaged in leisure activity|2=While working for income|3=While engaged in other types of work|4=While resting, sleeping, eating (vital activities)|8=While engaged in other specified activities|9=During unspecified activity|blank=Not applicable",
    "place_of_injury", 145, 145, 1, "int", "Place of injury", "0=Home|1=Residential institution|2=School, other institution and public administrative area|3=Sports and athletics area|4=Street and highway|5=Trade and service area|6=Industrial and construction area|7=Farm|8=Other Specified Places|9=Unspecified place|blank=Causes other than W00-Y34, except Y06.- and Y07.-",
    "icd_code", 146, 149, 4, "str", "ICD-10 code", "",
    "cause_recode_358", 150, 152, 3, "int", "358 cause recode", "",
    "reserved_6", 153, 153, 1, "str", "Reserved Position", "",
    "cause_recode_113", 154, 156, 3, "int", "113 cause recode", "",
    "infant_cause_recode_130", 157, 159, 3, "int", "130 infant cause recode", "",
    "cause_recode_39", 160, 161, 2, "int", "39 cause recode", "",
    "reserved_7", 162, 162, 1, "str", "Reserved Position", "",
    "num_entity_axis_conditions", 163, 164, 2, "int", "Number of entity-axis conditions", "",
    "entity_axis_conditions", 165, 304, 140, "str", "Entity-axis conditions (20 conditions, 7 chars each)", "",
    "reserved_8", 305, 340, 36, "str", "Reserved Positions", "",
    "num_record_axis_conditions", 341, 342, 2, "int", "Number of record-axis conditions", "",
    "reserved_9", 343, 343, 1, "str", "Reserved Position", "",
    "record_axis_conditions", 344, 443, 100, "str", "Record-axis conditions (20 conditions, 5 chars each)", "",
    "reserved_10", 444, 444, 1, "str", "Reserved Position", "",
    "race", 445, 446, 2, "int", "Race", "01=White|02=Black|03=American Indian|04=Chinese|05=Japanese|06=Hawaiian|07=Filipino|08=Asian Indian|09=Korean|10=Vietnamese|11=Other Asian|12=Guamanian|13=Samoan|14=Other Pacific Islander|18=Combined Asian/PI|28=Combined PI|38=Combined Asian|48=Combined AIAN|58=White/AIAN|68=White/Asian|78=Combined Asian/PI",
    "bridged_race_flag", 447, 447, 1, "int", "Bridged race flag", "blank=Not bridged|1=Bridged",
    "race_imputation_flag", 448, 448, 1, "int", "Race imputation flag", "blank=Not imputed|1=Unknown imputed|2=All other imputed",
    "race_recode_3", 449, 449, 1, "int", "Race recode 3", "1=White|2=Races other than White or Black|3=Black",
    "race_recode_5", 450, 450, 1, "int", "Race recode 5", "1=White|2=Black|3=American Indian|4=Asian/Pacific Islander",
    "reserved_11", 451, 483, 33, "str", "Reserved Positions", "",
    "hispanic_origin", 484, 486, 3, "int", "Hispanic origin", "100=Non-Hispanic|999=Unknown",
    "reserved_12", 487, 487, 1, "str", "Reserved Position", "",
    "hispanic_origin_race_recode", 488, 488, 1, "int", "Hispanic origin/race recode", "1=Mexican|2=Puerto Rican|3=Cuban|4=Central or South American|5=Other or unknown Hispanic|6=Non-Hispanic White|7=Non-Hispanic Black|8=Non-Hispanic other races|9=Hispanic origin unknown"
)
usethis::use_data(data_mortality_multiple_2010, overwrite = TRUE)
